/*
 * HTML LAB curriculum
 *
 * Materi dan challenge dipisahkan dari interface agar topik dapat diganti
 * dengan mudah. Setiap module memiliki satu challenge praktik utama.
 */
const moduleCatalog = [
  { id: 'm01', number: '01', icon: '&lt;/&gt;', title: 'Pengertian HTML', description: 'Pahami HTML sebagai bahasa markup untuk menyusun struktur web.', details: ['HTML adalah HyperText Markup Language.', 'HTML memberi struktur dan makna pada konten website.', 'HTML berbeda dari CSS yang mengatur tampilan dan JavaScript yang memberi interaksi.', 'HTML bukan bahasa pemrograman karena tidak memiliki logika, kondisi, atau perulangan.'] },
  { id: 'm02', number: '02', icon: '⌘', title: 'Struktur Dasar Dokumen HTML', description: 'Kenali kerangka dokumen yang dibaca browser.', details: ['<!DOCTYPE html> menandai standar HTML5.', 'html menjadi root element dokumen.', 'head berisi metadata, title, dan resource pendukung.', 'body berisi konten yang terlihat oleh pengguna.', 'Tag umumnya memiliki opening tag dan closing tag.'] },
  { id: 'm03', number: '03', icon: '◈', title: 'Tag, Element, dan Attribute', description: 'Bedakan tag, element, attribute, dan void element.', details: ['Tag adalah penanda seperti p atau img.', 'Element terdiri dari opening tag, isi, dan closing tag.', 'Attribute memberi informasi tambahan pada opening tag.', 'img dan input adalah void element yang tidak memiliki closing tag.', 'Contoh: <p>, <img>, dan <input>.'] },
  { id: 'm04', number: '04', icon: 'H1', title: 'Tag Heading', description: 'Bangun hierarki judul dari h1 sampai h6.', details: ['h1 adalah heading paling utama.', 'h2 sampai h6 membentuk sub-hierarki.', 'Gunakan heading berdasarkan struktur, bukan hanya ukuran font.', 'Hindari melompat-lompat level heading tanpa alasan.'] },
  { id: 'm05', number: '05', icon: '¶', title: 'Paragraf dan Pemisah Teks', description: 'Susun teks dengan p, br, dan hr secara terstruktur.', details: ['p digunakan untuk satu blok paragraf.', 'br membuat perpindahan baris di dalam konteks yang sama.', 'hr menandai perubahan topik atau thematic break.', 'Jangan memakai banyak br hanya untuk mengatur layout.'] },
  { id: 'm06', number: '06', icon: 'Aa', title: 'Format Teks', description: 'Gunakan elemen format teks sesuai makna kontennya.', details: ['strong menandai kepentingan kuat, sedangkan b hanya visual tebal.', 'em memberi penekanan, sedangkan i hanya gaya miring.', 'u, mark, small, del, ins, sub, dan sup punya konteks masing-masing.', 'Pilih semantic element sebelum memikirkan tampilan.'] },
  { id: 'm07', number: '07', icon: '↗', title: 'Link dan Hyperlink', description: 'Hubungkan halaman, bagian halaman, email, dan telepon.', details: ['a membuat hyperlink.', 'href menentukan tujuan link.', 'Gunakan relative link untuk halaman dalam project.', 'Gunakan absolute link untuk website eksternal.', 'target="_blank" membuka tab baru; link email memakai mailto dan telepon memakai tel.'] },
  { id: 'm08', number: '08', icon: '▧', title: 'Gambar', description: 'Tampilkan gambar dengan src, alt, ukuran, dan path yang benar.', details: ['img adalah void element.', 'src menunjuk lokasi file gambar.', 'alt wajib menjelaskan gambar untuk aksesibilitas.', 'width dan height memberi dimensi awal.', 'Pahami perbedaan relative path dan absolute path.'] },
  { id: 'm09', number: '09', icon: '☷', title: 'List', description: 'Buat daftar terurut, tidak terurut, bertingkat, dan deskripsi.', details: ['ol menampilkan daftar berurutan.', 'ul menampilkan daftar tanpa urutan.', 'li adalah item di dalam ol atau ul.', 'List dapat dibuat nested.', 'dl, dt, dan dd cocok untuk daftar istilah dan deskripsi.'] },
  { id: 'm10', number: '10', icon: '▣', title: 'Container', description: 'Kelompokkan elemen dengan div dan span.', details: ['div adalah container block-level generik.', 'span adalah container inline generik.', 'Container membantu pengelompokan dan styling.', 'Gunakan semantic element jika sudah ada makna yang lebih tepat.'] },
  { id: 'm11', number: '11', icon: '⌑', title: 'Semantic HTML5', description: 'Susun halaman dengan elemen yang memiliki makna.', details: ['header berisi pengantar atau area atas.', 'nav berisi navigasi utama.', 'main menandai konten utama.', 'section, article, aside, dan footer membagi konteks halaman.', 'Semantic HTML membantu SEO, aksesibilitas, dan pemeliharaan kode.'] },
  { id: 'm12', number: '12', icon: '▤', title: 'Tabel', description: 'Tampilkan data tabular dengan struktur yang benar.', details: ['table membungkus data tabular.', 'tr adalah baris, th adalah sel header, td adalah sel data.', 'thead, tbody, dan tfoot mengelompokkan bagian tabel.', 'colspan menggabungkan kolom.', 'rowspan menggabungkan baris.'] },
  { id: 'm13', number: '13', icon: '⌁', title: 'Form', description: 'Buat form dengan field, label, pilihan, dan tombol.', details: ['form membungkus data yang dikirim.', 'label menjelaskan field.', 'input, textarea, select, option, dan button adalah kontrol form.', 'fieldset mengelompokkan field dan legend memberi judul kelompok.', 'Gunakan hubungan label-for dan input-id.'] },
  { id: 'm14', number: '14', icon: '◉', title: 'Jenis Input HTML', description: 'Pilih jenis input sesuai tipe data yang diminta.', details: ['text dan password untuk teks biasa atau rahasia.', 'email, number, dan date memberi validasi bawaan browser.', 'radio dan checkbox untuk pilihan.', 'file, color, dan range memberi kontrol khusus.', 'submit dan reset mengatur aksi form.'] },
  { id: 'm15', number: '15', icon: '⚙', title: 'Attribute Form', description: 'Kendalikan perilaku field dengan attribute penting.', details: ['name menjadi kunci data saat form dikirim.', 'value memberi nilai awal.', 'placeholder memberi petunjuk singkat.', 'required, readonly, dan disabled mengatur status field.', 'min, max, maxlength, checked, dan selected memberi batas atau pilihan awal.'] },
  { id: 'm16', number: '16', icon: '▶', title: 'Multimedia', description: 'Sematkan audio dan video dengan kontrol yang tepat.', details: ['audio dan video menampilkan media native browser.', 'source memungkinkan beberapa format file.', 'controls menampilkan kontrol pemutar.', 'autoplay, loop, dan muted mengatur perilaku pemutaran.', 'Pertimbangkan bandwidth dan aksesibilitas media.'] },
  { id: 'm17', number: '17', icon: '▤', title: 'Embed dan Konten Eksternal', description: 'Tampilkan konten dari sumber luar memakai iframe.', details: ['iframe menanamkan dokumen atau media eksternal.', 'Video YouTube dapat ditampilkan melalui URL embed.', 'Halaman eksternal tidak selalu mengizinkan embedding.', 'Pertimbangkan sandbox, allow, origin, dan risiko keamanan.'] },
  { id: 'm18', number: '18', icon: '&amp;', title: 'HTML Entities', description: 'Tampilkan karakter khusus dengan entity yang aman.', details: ['&lt; menampilkan tanda kurang dari.', '&gt; menampilkan tanda lebih dari.', '&amp; menampilkan ampersand.', '&nbsp; membuat non-breaking space.', '&copy; menampilkan simbol copyright.'] },
  { id: 'm19', number: '19', icon: '//', title: 'Komentar HTML', description: 'Dokumentasikan kode tanpa menampilkannya di browser.', details: ['Komentar ditulis dengan <!-- komentar -->.', 'Komentar tidak dirender sebagai konten halaman.', 'Gunakan komentar untuk konteks singkat.', 'Jangan memasukkan password atau data rahasia ke komentar.'] },
  { id: 'm20', number: '20', icon: 'id', title: 'Attribute Global', description: 'Gunakan id, class, style, title, hidden, lang, dan data-*.', details: ['id harus unik dalam satu halaman.', 'class dapat dipakai oleh banyak elemen.', 'style menulis inline style, tetapi CSS eksternal lebih terawat.', 'title memberi informasi tambahan.', 'hidden, lang, dan data-* punya fungsi umum lintas elemen.'] },
  { id: 'm21', number: '21', icon: '#', title: 'ID dan Class', description: 'Pahami identitas unik dan pengelompokan elemen.', details: ['Satu id idealnya hanya dipakai satu elemen.', 'Satu elemen dapat memiliki beberapa class.', 'CSS memakai selector id dan class.', 'JavaScript dapat mengambil elemen melalui id atau class.', 'Gunakan nama yang deskriptif dan konsisten.'] },
  { id: 'm22', number: '22', icon: '▤', title: 'Block dan Inline Element', description: 'Pahami pengaruh jenis elemen terhadap layout.', details: ['Block element biasanya mengambil lebar penuh dan mulai baris baru.', 'Inline element mengikuti aliran teks.', 'div dan p adalah contoh block.', 'span dan a adalah contoh inline.', 'CSS dapat mengubah perilaku display.'] },
  { id: 'm23', number: '23', icon: '⌞', title: 'Nesting HTML', description: 'Susun elemen di dalam elemen dengan urutan yang valid.', details: ['Nesting berarti menempatkan elemen di dalam elemen lain.', 'Tag terakhir yang dibuka harus ditutup lebih dahulu.', 'Elemen harus berada di parent yang sesuai.', 'Nesting yang rapi membantu browser dan aksesibilitas.'] },
  { id: 'm24', number: '24', icon: '../', title: 'Relative dan Absolute Path', description: 'Arahkan file dengan path yang tepat.', details: ['Relative path dihitung dari lokasi file aktif.', '../ naik satu folder.', '/ mengarah dari root sesuai konteks hosting.', 'Absolute URL menyertakan protocol dan domain.', 'Kesalahan path sering menyebabkan gambar atau link 404.'] },
  { id: 'm25', number: '25', icon: '⌂', title: 'Struktur Folder Website', description: 'Susun file project agar mudah dikembangkan.', details: ['index.html menjadi entry point umum.', 'images menyimpan aset visual.', 'css menyimpan stylesheet.', 'js menyimpan script.', 'pages dapat menyimpan halaman tambahan.'] },
  { id: 'm26', number: '26', icon: '✓', title: 'Validasi HTML', description: 'Temukan tag, nesting, id, dan attribute yang bermasalah.', details: ['HTML valid mengikuti aturan syntax.', 'Pastikan tag tertutup dan nesting benar.', 'Hindari duplicate id.', 'Gunakan attribute yang sesuai untuk elemen.', 'Validator membantu menemukan kesalahan lebih awal.'] },
  { id: 'm27', number: '27', icon: '◌', title: 'Accessibility Dasar', description: 'Buat halaman yang dapat digunakan lebih banyak orang.', details: ['Selalu beri alt yang bermakna pada gambar.', 'Hubungkan label dengan input.', 'Jaga hierarki heading.', 'Gunakan semantic HTML.', 'Pastikan kontrol dapat dijangkau dengan keyboard.'] },
  { id: 'm28', number: '28', icon: '⌕', title: 'SEO Dasar', description: 'Bantu mesin pencari memahami isi halaman.', details: ['title tampil di tab dan hasil pencarian.', 'meta description memberi ringkasan halaman.', 'Heading membantu memahami hierarki topik.', 'Semantic HTML memberi konteks konten.', 'Buat deskripsi yang unik dan relevan.'] },
  { id: 'm29', number: '29', icon: '✦', title: 'Best Practice HTML', description: 'Tulis HTML yang rapi, konsisten, dan mudah dirawat.', details: ['Gunakan indentasi konsisten.', 'Pakai nama file yang jelas.', 'Gunakan huruf kecil untuk nama tag dan attribute.', 'Pisahkan HTML, CSS, dan JavaScript.', 'Hindari tag deprecated dan prioritaskan semantic HTML.'] },
  { id: 'm30', number: '30', icon: '✺', title: 'Halaman HTML Lengkap', description: 'Gabungkan seluruh fondasi menjadi satu halaman nyata.', details: ['Halaman dapat memiliki title, header, dan navigasi.', 'main dapat memuat profil, gambar, list, dan tabel.', 'Form kontak menghubungkan pengguna dengan halaman.', 'footer menutup struktur halaman.', 'Gunakan semantic HTML, aksesibilitas, dan struktur folder yang rapi.'] }
];

const questions = [
  { id: 'html-01', module: 'm01', title: 'Show the HTML idea', prompt: 'Buat paragraf yang menjelaskan “HTML menyusun struktur halaman.”', lessonTitle: 'HTML sebagai markup', lessonBody: 'HTML menggunakan tag untuk memberi makna dan struktur pada konten. Browser membaca struktur tersebut lalu menampilkannya sebagai halaman.', lessonCode: '<p>HTML menyusun struktur halaman.</p>', starter: '<!-- Tulis satu paragraf tentang HTML -->', required: ['<p[^>]*>\\s*html menyusun struktur halaman\\.\\s*</p>'] },
  { id: 'html-02', module: 'm02', title: 'Build the document skeleton', prompt: 'Tulis deklarasi HTML5, html lang="id", dan elemen body.', lessonTitle: 'Kerangka dokumen', lessonBody: 'Dokumen HTML memiliki root html, metadata di head, dan konten yang dilihat pengguna di body.', lessonCode: '<!doctype html>\n<html lang="id">\n  <body>...</body>\n</html>', starter: '<!-- Lengkapi kerangka dokumen -->', required: ['<!doctype\\s+html>'] },
  { id: 'html-03', module: 'm03', title: 'Add meaning with an attribute', prompt: 'Buat paragraf class="intro" berisi teks “Halo, web!”.', lessonTitle: 'Element dan attribute', lessonBody: 'Element menyatukan tag dan konten. Attribute seperti class ditempatkan di opening tag untuk memberi informasi tambahan.', lessonCode: '<p class="intro">Halo, web!</p>', starter: '<!-- Buat paragraf dengan attribute class -->', required: ['<p[^>]*class\\s*=\\s*["\']intro["\'][^>]*>\\s*halo, web!\\s*</p>'] },
  { id: 'html-04', module: 'm04', title: 'Create the main heading', prompt: 'Buat h1 dengan teks “Belajar Web”.', lessonTitle: 'Hierarki heading', lessonBody: 'Heading h1 sampai h6 menyusun hierarki informasi. Gunakan level berdasarkan struktur topik, bukan sekadar ukuran visual.', lessonCode: '<h1>Belajar Web</h1>', starter: '<!-- Heading utama -->', required: ['<h1[^>]*>\\s*belajar web\\s*</h1>'] },
  { id: 'html-05', module: 'm05', title: 'Separate the content', prompt: 'Buat paragraf “Baris pertama”, line break, lalu thematic break.', lessonTitle: 'Pemisah teks', lessonBody: 'p membungkus paragraf, br membuat line break dalam konteks yang sama, dan hr menandai perpindahan topik.', lessonCode: '<p>Baris pertama</p>\n<br>\n<hr>', starter: '<!-- Paragraf, line break, dan pemisah -->', required: ['<p[^>]*>\\s*baris pertama\\s*</p>'] },
  { id: 'html-06', module: 'm06', title: 'Mark important text', prompt: 'Buat teks “Penting” dengan strong dan teks “catatan” dengan em.', lessonTitle: 'Makna format teks', lessonBody: 'Gunakan strong dan em ketika format tersebut memiliki makna. b dan i sebaiknya dipilih hanya ketika kebutuhan visual tidak memiliki arti semantik.', lessonCode: '<strong>Penting</strong>\n<em>catatan</em>', starter: '<!-- Format teks semantic -->', required: ['<strong[^>]*>\\s*penting\\s*</strong>'] },
  { id: 'html-07', module: 'm07', title: 'Connect a page', prompt: 'Buat link “Tentang kelas” menuju pages/about.html dan link “Buka MDN” ke website eksternal pada tab baru.', lessonTitle: 'Hyperlink', lessonBody: 'href adalah tujuan anchor. Relative link cocok untuk project sendiri, sedangkan absolute link digunakan untuk sumber eksternal.', lessonCode: '<a href="pages/about.html">Tentang kelas</a>\n<a href="https://developer.mozilla.org" target="_blank">Buka MDN</a>', starter: '<!-- Buat dua hyperlink -->', required: ['<a[^>]*href\\s*=\\s*["\']pages/about\\.html["\']'], },
  { id: 'html-08', module: 'm08', title: 'Describe an image', prompt: 'Tampilkan gambar images/logo.png dengan alt “Logo HTML Lab”, width 240, dan height 120.', lessonTitle: 'Gambar dan alternative text', lessonBody: 'src menentukan file, alt menjelaskan gambar kepada pengguna screen reader atau saat gambar gagal dimuat. width dan height membantu browser menyiapkan ruang.', lessonCode: '<img src="images/logo.png" alt="Logo HTML Lab" width="240" height="120">', starter: '<!-- Gambar dengan informasi lengkap -->', required: ['<img[^>]*src\\s*=\\s*["\']images/logo\\.png["\']'] },
  { id: 'html-09', module: 'm09', title: 'Make a clean list', prompt: 'Buat unordered list berisi HTML, CSS, dan JavaScript.', lessonTitle: 'Unordered list', lessonBody: 'ul cocok untuk kumpulan item yang urutannya tidak penting. Setiap item harus berada di dalam li.', lessonCode: '<ul>\n  <li>HTML</li>\n  <li>CSS</li>\n  <li>JavaScript</li>\n</ul>', starter: '<!-- Daftar teknologi web -->', required: ['<ul[^>]*>[\\s\\S]*<li[^>]*>\\s*html\\s*</li>[\\s\\S]*<li[^>]*>\\s*css\\s*</li>[\\s\\S]*</ul>'] },
  { id: 'html-10', module: 'm10', title: 'Group block and inline content', prompt: 'Buat div berisi span dengan teks “HTML Lab”.', lessonTitle: 'Container div dan span', lessonBody: 'div adalah container block-level, sedangkan span adalah container inline. Keduanya generik dan sering dipakai bersama class atau id.', lessonCode: '<div class="card"><span>HTML Lab</span></div>', starter: '<!-- Container block dan inline -->', required: ['<div[^>]*>[\\s\\S]*<span[^>]*>\\s*html lab\\s*</span>[\\s\\S]*</div>'] },
  { id: 'html-11', module: 'm11', title: 'Compose a semantic layout', prompt: 'Buat layout yang memiliki header, nav, main, section, article, aside, dan footer.', lessonTitle: 'Semantic HTML5', lessonBody: 'Elemen semantic mengomunikasikan peran konten. Struktur yang bermakna lebih mudah dipahami browser, mesin pencari, screen reader, dan developer lain.', lessonCode: '<header>...</header>\n<nav>...</nav>\n<main><section><article>...</article></section><aside>...</aside></main>\n<footer>...</footer>', starter: '<!-- Susun landmark semantic halaman -->', required: ['<header'] },
  { id: 'html-12', module: 'm12', title: 'Create a data table', prompt: 'Buat tabel dengan thead berisi Nama dan Skor, tbody berisi Ana dan 90, serta tfoot.', lessonTitle: 'Table anatomy', lessonBody: 'Tabel digunakan untuk data yang memiliki hubungan baris dan kolom. Kelompokkan header, isi, dan ringkasan dengan thead, tbody, dan tfoot.', lessonCode: '<table>\n  <thead><tr><th>Nama</th><th>Skor</th></tr></thead>\n  <tbody><tr><td>Ana</td><td>90</td></tr></tbody>\n  <tfoot><tr><td colspan="2">Rata-rata kelas</td></tr></tfoot>\n</table>', starter: '<!-- Tabel hasil belajar -->', required: ['<table'] },
  { id: 'html-13', module: 'm13', title: 'Build a contact form', prompt: 'Buat form berisi field nama, textarea pesan, select topik, dan button Kirim.', lessonTitle: 'Form controls', lessonBody: 'Form menghubungkan input pengguna dengan proses pengiriman. Label harus terhubung dengan field agar form mudah dipakai.', lessonCode: '<form>\n  <label for="name">Nama</label>\n  <input id="name" name="name">\n  <textarea name="message"></textarea>\n  <select name="topic"><option>HTML</option></select>\n  <button type="submit">Kirim</button>\n</form>', starter: '<!-- Form kontak -->', required: ['<form'] },
  { id: 'html-14', module: 'm14', title: 'Choose the right input', prompt: 'Buat input text, password, email, number, date, radio, checkbox, file, color, range, submit, dan reset.', lessonTitle: 'Input types', lessonBody: 'Type input memberi petunjuk kepada browser tentang jenis data dan kontrol yang tepat. Pilih type yang paling sesuai dengan kebutuhan pengguna.', lessonCode: '<input type="email" name="email">\n<input type="date" name="birth-date">\n<input type="checkbox" name="agree">', starter: '<!-- Kumpulan input untuk form -->', required: ['<input'] },
  { id: 'html-15', module: 'm15', title: 'Configure form attributes', prompt: 'Buat input email dengan name, value, placeholder, required, maxlength, min, max, dan readonly. Tambahkan checkbox checked serta option selected.', lessonTitle: 'Form attributes', lessonBody: 'Attribute form mengatur nama data, nilai awal, petunjuk, validasi, batas, dan status field sebelum data dikirim.', lessonCode: '<input type="email" name="email" value="student@example.com" placeholder="Email aktif" required maxlength="80" readonly>\n<input type="number" min="1" max="100">\n<input type="checkbox" checked>\n<option selected>HTML</option>', starter: '<!-- Input dengan attribute lengkap -->', required: ['<input[^>]*\\brequired'] },
  { id: 'html-16', module: 'm16', title: 'Add media controls', prompt: 'Buat audio dan video dengan controls, loop, serta video muted.', lessonTitle: 'Audio, video, source', lessonBody: 'audio dan video memiliki kontrol bawaan. source memungkinkan browser memilih format yang didukung. autoplay perlu digunakan dengan pertimbangan pengalaman pengguna.', lessonCode: '<audio controls loop><source src="intro.mp3" type="audio/mpeg"></audio>\n<video controls loop muted><source src="intro.mp4" type="video/mp4"></video>', starter: '<!-- Media pembelajaran -->', required: ['<(audio|video)'] },
  { id: 'html-17', module: 'm17', title: 'Embed external content', prompt: 'Sematkan video YouTube menggunakan iframe dengan title yang jelas.', lessonTitle: 'Iframe dan keamanan', lessonBody: 'iframe menampilkan dokumen eksternal di dalam halaman. Gunakan URL embed yang benar, title yang deskriptif, dan pertimbangkan sandbox serta permission.', lessonCode: '<iframe src="https://www.youtube.com/embed/VIDEO_ID" title="Video pengantar HTML"></iframe>', starter: '<!-- Embed video eksternal -->', required: ['<iframe[^>]*\\bsrc'] },
  { id: 'html-18', module: 'm18', title: 'Show reserved characters', prompt: 'Tampilkan teks literal “<h1>HTML</h1> & aman” menggunakan HTML entities.', lessonTitle: 'HTML entities', lessonBody: 'Entity diperlukan ketika karakter tertentu memiliki arti khusus bagi parser HTML. Dengan entity, simbol dapat tampil sebagai teks biasa.', lessonCode: '<p>&lt;h1&gt;HTML&lt;/h1&gt; &amp; aman</p>', starter: '<!-- Tampilkan contoh tag sebagai teks -->', required: ['&lt;h1&gt;'] },
  { id: 'html-19', module: 'm19', title: 'Document your code', prompt: 'Tambahkan komentar “Bagian utama” lalu paragraf “Konten halaman”.', lessonTitle: 'Komentar HTML', lessonBody: 'Komentar membantu dokumentasi singkat dan tidak muncul sebagai konten browser. Jangan menyimpan informasi rahasia di dalam komentar.', lessonCode: '<!-- Bagian utama -->\n<p>Konten halaman</p>', starter: '<!-- Tulis komentar dokumentasi dan paragraf -->', required: ['<!--\\s*bagian utama\\s*-->'] },
  { id: 'html-20', module: 'm20', title: 'Use global attributes', prompt: 'Buat div id="app", class="card", title="Kartu profil", data-state="ready", dan lang="id".', lessonTitle: 'Global attributes', lessonBody: 'Attribute global dapat digunakan lintas elemen. id, class, title, lang, dan data-* sering menjadi penghubung HTML dengan CSS atau JavaScript.', lessonCode: '<div id="app" class="card" title="Kartu profil" data-state="ready" lang="id">Profil</div>', starter: '<!-- Elemen dengan global attributes -->', required: ['<div[^>]*\\bid\\s*='] },
  { id: 'html-21', module: 'm21', title: 'Separate identity and style', prompt: 'Buat section id="profile" dengan dua class: card dan highlight.', lessonTitle: 'ID dan class', lessonBody: 'id memberi identitas unik, sedangkan class mengelompokkan elemen. Satu element boleh memiliki beberapa class yang dipisahkan spasi.', lessonCode: '<section id="profile" class="card highlight">Profil mahasiswa</section>', starter: '<!-- Section dengan id dan beberapa class -->', required: ['<section[^>]*\\bid\\s*='] },
  { id: 'html-22', module: 'm22', title: 'Compare block and inline', prompt: 'Buat div bertuliskan “Block” dan span bertuliskan “Inline”.', lessonTitle: 'Block vs inline', lessonBody: 'Block element memulai baris baru, inline element mengikuti aliran teks. Perilaku ini memengaruhi layout sebelum CSS diterapkan.', lessonCode: '<div>Block</div>\n<span>Inline</span>', starter: '<!-- Satu block dan satu inline element -->', required: ['<div[^>]*>\\s*block\\s*</div>[\\s\\S]*<span[^>]*>\\s*inline\\s*</span>'] },
  { id: 'html-23', module: 'm23', title: 'Nest with care', prompt: 'Buat paragraf yang berisi strong “HTML” lalu teks “ rapi.”.', lessonTitle: 'Nesting yang benar', lessonBody: 'Nesting harus mengikuti urutan pembukaan dan penutupan. Elemen child ditutup sebelum parent-nya ditutup.', lessonCode: '<p><strong>HTML</strong> rapi.</p>', starter: '<!-- Susun elemen dengan nesting benar -->', required: ['<p[^>]*>[\\s\\S]*<strong[^>]*>\\s*html\\s*</strong>[\\s\\S]*</p>'] },
  { id: 'html-24', module: 'm24', title: 'Point to an asset', prompt: 'Tampilkan logo dari relative path ../images/logo.png dengan alt “Logo”.', lessonTitle: 'Relative dan absolute path', lessonBody: 'Relative path dihitung dari lokasi file saat ini. ../ naik satu folder, sedangkan URL lengkap adalah absolute path.', lessonCode: '<img src="../images/logo.png" alt="Logo">', starter: '<!-- Akses gambar dari folder parent -->', required: ['<img[^>]*\\bsrc\\s*=\\s*["\']\\.\\./images/logo\\.png["\']'] },
  { id: 'html-25', module: 'm25', title: 'Link your project folders', prompt: 'Buat link ke pages/about.html dan hubungkan stylesheet css/style.css.', lessonTitle: 'Struktur folder website', lessonBody: 'Project sederhana dapat memisahkan halaman, gambar, CSS, dan JavaScript ke folder masing-masing agar mudah dipelihara.', lessonCode: '<head><link rel="stylesheet" href="css/style.css"></head>\n<a href="pages/about.html">Tentang</a>', starter: '<!-- Hubungkan file project -->', required: ['<link[^>]*href\\s*=\\s*["\']css/style\\.css["\']'] },
  { id: 'html-26', module: 'm26', title: 'Write valid structure', prompt: 'Buat dokumen valid dengan doctype, html lang="id", title, dan paragraf yang tag-nya tertutup.', lessonTitle: 'Validasi HTML', lessonBody: 'HTML yang valid mengurangi perilaku browser yang tidak terduga. Periksa tag penutup, nesting, duplicate id, dan attribute sebelum dipublikasikan.', lessonCode: '<!doctype html>\n<html lang="id"><head><title>Valid</title></head><body><p>Rapi</p></body></html>', starter: '<!-- Buat struktur valid -->', required: ['<!doctype\\s+html>'] },
  { id: 'html-27', module: 'm27', title: 'Make the image accessible', prompt: 'Buat label “Foto profil” yang terhubung ke input file dan gambar dengan alt yang bermakna.', lessonTitle: 'Accessibility dasar', lessonBody: 'Alt, label, hierarki heading, semantic HTML, dan keyboard access membantu lebih banyak orang menggunakan halaman web.', lessonCode: '<label for="photo">Foto profil</label>\n<input id="photo" type="file">\n<img src="profile.png" alt="Potret mahasiswa">', starter: '<!-- Form foto yang aksesibel -->', required: ['<label[^>]*\\bfor'] },
  { id: 'html-28', module: 'm28', title: 'Give the page SEO signals', prompt: 'Buat title “HTML Lab” dan meta description “Belajar HTML dari dasar.”.', lessonTitle: 'SEO dari struktur HTML', lessonBody: 'Title, meta description, heading, dan semantic HTML membantu mesin pencari memahami halaman serta menampilkan cuplikan yang relevan.', lessonCode: '<title>HTML Lab</title>\n<meta name="description" content="Belajar HTML dari dasar.">', starter: '<!-- Metadata SEO halaman -->', required: ['<title'] },
  { id: 'html-29', module: 'm29', title: 'Write clean HTML', prompt: 'Buat dokumen kecil dengan huruf kecil pada tag, indentasi rapi, dan pisahkan link CSS.', lessonTitle: 'Best practice', lessonBody: 'Kode rapi, penamaan jelas, huruf kecil, pemisahan concern, dan penggunaan elemen modern membuat project lebih mudah dirawat.', lessonCode: '<link rel="stylesheet" href="css/style.css">\n<main>\n  <h1>HTML Lab</h1>\n</main>', starter: '<!-- HTML yang rapi dan terpisah dari CSS -->', required: ['<link[^>]*rel\\s*='] },
  { id: 'html-30', module: 'm30', title: 'Ship a complete page', prompt: 'Gabungkan header, nav, main berisi section profil, dan footer menjadi satu halaman HTML.', lessonTitle: 'Halaman lengkap', lessonBody: 'Challenge terakhir menggabungkan struktur, semantic HTML, navigasi, konten, dan penutup halaman menjadi satu fondasi website yang siap dikembangkan.', lessonCode: '<header><h1>HTML Lab</h1></header>\n<nav><a href="/">Beranda</a></nav>\n<main><section><h2>Profil</h2></section></main>\n<footer>© 2026 HTML Lab</footer>', starter: '<!-- Bangun satu halaman lengkap -->', required: ['<header'] }
];

const detailedNotes = {
  m01: { explanation: 'HTML adalah bahasa markup yang memberi struktur, hierarki, dan arti pada konten web. Browser tidak menjalankan HTML seperti program; browser membaca elemen lalu membangun DOM yang dapat ditampilkan, dicari, dan dibaca teknologi bantu.', example: '<h1>Profil Mahasiswa</h1>\n<p>HTML menyusun struktur halaman.</p>' },
  m02: { explanation: 'Dokumen HTML5 dimulai dengan doctype, lalu satu root html. Metadata diletakkan di head, sedangkan konten visual berada di body. Setiap elemen berpasangan harus ditutup dengan urutan yang benar.', example: '<!doctype html>\n<html lang="id">\n  <head><title>HTML Lab</title></head>\n  <body>Konten</body>\n</html>' },
  m03: { explanation: 'Tag adalah penanda seperti p. Element adalah tag beserta isi dan penutupnya. Attribute berada di opening tag dan memberi konfigurasi atau identitas. Void element seperti img dan input tidak memiliki closing tag.', example: '<p class="intro">Halo</p>\n<img src="logo.png" alt="Logo">\n<input type="email">' },
  m04: { explanation: 'Heading menyatakan struktur topik, bukan sekadar ukuran huruf. Mulai dengan satu h1 sebagai judul halaman, gunakan h2 untuk bagian utama, lalu h3 dan seterusnya untuk subbagian.', example: '<h1>Belajar HTML</h1>\n<h2>Struktur Dokumen</h2>\n<h3>Elemen body</h3>' },
  m05: { explanation: 'Paragraf adalah unit informasi yang berdiri sendiri. br hanya untuk perpindahan baris yang memang bermakna, sedangkan hr menandai jeda atau perubahan topik. Spasi layout sebaiknya dikerjakan oleh CSS.', example: '<p>Baris pertama</p>\n<br>\n<hr>\n<p>Topik berikutnya</p>' },
  m06: { explanation: 'Gunakan strong untuk kepentingan kuat dan em untuk penekanan. b dan i hanya menyatakan tampilan visual. mark menyorot, del menandai hapus, ins menandai tambahan, small untuk catatan, sedangkan sub dan sup untuk indeks.', example: '<p><strong>Penting</strong> dan <em>perhatikan</em> bagian ini.</p>\n<p>H<sub>2</sub>O · x<sup>2</sup></p>' },
  m07: { explanation: 'Anchor menghubungkan pengguna ke tujuan. href dapat berisi path internal, URL eksternal, fragment #id, mailto, atau tel. Saat memakai target blank, pertimbangkan keamanan dan pengalaman pengguna.', example: '<a href="pages/about.html">Tentang</a>\n<a href="https://developer.mozilla.org" target="_blank">MDN</a>\n<a href="mailto:lab@example.com">Email</a>' },
  m08: { explanation: 'Gambar membutuhkan src yang benar dan alt yang menjelaskan makna gambar. Jangan mengulang kata “gambar” di alt jika tidak perlu. Relative path mengikuti posisi file HTML, sedangkan absolute path menunjuk alamat lengkap.', example: '<img src="images/logo.png" alt="Logo HTML Lab" width="240" height="120">' },
  m09: { explanation: 'Gunakan ul ketika urutan tidak penting dan ol ketika urutan memiliki makna. li adalah satu item. List dapat bersarang dengan menempatkan ul atau ol di dalam li. Gunakan dl untuk istilah dan deskripsi pasangannya.', example: '<ol>\n  <li>Riset</li>\n  <li>Kode</li>\n</ol>\n<dl><dt>HTML</dt><dd>Struktur web</dd></dl>' },
  m10: { explanation: 'div dan span tidak membawa arti khusus, tetapi berguna sebagai container. div mengikuti perilaku block, span mengikuti inline. Tambahkan class atau id agar container dapat ditargetkan CSS dan JavaScript.', example: '<div class="card">\n  <span class="label">HTML Lab</span>\n</div>' },
  m11: { explanation: 'Semantic HTML menggunakan nama elemen berdasarkan perannya. Landmark seperti header, nav, main, section, article, aside, dan footer membuat struktur lebih mudah dipahami tanpa bergantung pada class buatan.', example: '<header>Logo</header>\n<nav>Menu</nav>\n<main><section><article>Konten</article></section></main>\n<footer>Copyright</footer>' },
  m12: { explanation: 'Tabel hanya untuk data yang memiliki relasi baris dan kolom. th menjelaskan kolom atau baris, td berisi data. Kelompok thead, tbody, dan tfoot membantu struktur; colspan dan rowspan menggabungkan sel.', example: '<table>\n  <thead><tr><th>Nama</th><th>Skor</th></tr></thead>\n  <tbody><tr><td>Ana</td><td>90</td></tr></tbody>\n</table>' },
  m13: { explanation: 'Form mengumpulkan input pengguna. Label harus terhubung lewat for dan id. Fieldset mengelompokkan kontrol yang berhubungan, legend memberi judul kelompok, dan button menentukan aksi yang dapat dilakukan.', example: '<form>\n  <label for="name">Nama</label>\n  <input id="name" name="name">\n  <button type="submit">Kirim</button>\n</form>' },
  m14: { explanation: 'Jenis input menentukan kontrol dan validasi bawaan browser. Pilih type sesuai data: email untuk email, date untuk tanggal, number untuk angka, radio untuk satu pilihan, dan checkbox untuk pilihan jamak.', example: '<input type="email" name="email">\n<input type="date" name="birth-date">\n<input type="checkbox" name="agree">' },
  m15: { explanation: 'Attribute form mengontrol data dan interaksi. name menjadi kunci saat dikirim, value menjadi nilai awal, placeholder memberi contoh, required memaksa pengisian, dan readonly atau disabled mengubah status interaksi.', example: '<input name="score" value="90" placeholder="Skor" min="0" max="100" required>' },
  m16: { explanation: 'audio dan video menampilkan media native. controls memberi kontrol pengguna, source menyediakan format alternatif, loop mengulang, muted membisukan, dan autoplay sebaiknya dipakai sangat hati-hati.', example: '<video controls muted loop>\n  <source src="intro.mp4" type="video/mp4">\n</video>' },
  m17: { explanation: 'iframe membuat browsing context di dalam halaman. Gunakan URL embed resmi, title yang menjelaskan isi, dan atribut keamanan seperti sandbox atau allow sesuai kebutuhan. Tidak semua situs mengizinkan dirinya ditanamkan.', example: '<iframe src="https://www.youtube.com/embed/VIDEO_ID" title="Video HTML" sandbox></iframe>' },
  m18: { explanation: 'Parser HTML memperlakukan <, >, dan & sebagai bagian syntax. Gunakan entity ketika simbol tersebut ingin ditampilkan sebagai teks, terutama saat mendokumentasikan contoh kode HTML.', example: '<p>&lt;h1&gt;HTML&lt;/h1&gt; &amp; aman</p>\n<p>&copy; 2026</p>' },
  m19: { explanation: 'Komentar adalah catatan developer yang tidak dirender. Komentar bermanfaat untuk menjelaskan alasan atau pembagian kode, tetapi seluruh isi komentar tetap dapat dilihat dari source sehingga bukan tempat menyimpan rahasia.', example: '<!-- Bagian utama halaman -->\n<main>Konten</main>' },
  m20: { explanation: 'Attribute global dapat digunakan di banyak elemen. id harus unik, class boleh berulang, title memberi tooltip atau konteks, hidden menyembunyikan elemen, lang menyatakan bahasa, dan data-* menyimpan metadata custom.', example: '<div id="app" class="card" lang="id" data-state="ready" title="Kartu profil">Profil</div>' },
  m21: { explanation: 'Gunakan id untuk satu target unik, misalnya anchor atau field form. Gunakan class untuk pola yang berulang. Beberapa class pada satu elemen dipisahkan spasi dan dapat dipakai sebagai kombinasi selector.', example: '<section id="profile" class="card highlight">Profil</section>' },
  m22: { explanation: 'Block element memulai baris baru dan biasanya mengambil ruang horizontal yang tersedia. Inline element mengikuti aliran teks. Perbedaan ini adalah perilaku default dan dapat diubah melalui CSS display.', example: '<div>Block element</div>\n<span>Inline element</span>' },
  m23: { explanation: 'Nesting menempatkan child di dalam parent. Tutup tag dengan prinsip last opened, first closed. Nesting yang benar menjaga DOM tetap logis dan mencegah browser melakukan perbaikan markup yang tidak diinginkan.', example: '<p><strong>HTML</strong> rapi.</p>' },
  m24: { explanation: 'Relative path dihitung dari file aktif: images/logo.png berada di folder anak, ../images/logo.png naik satu tingkat, dan / bergantung pada root hosting. Absolute URL berisi protocol dan domain lengkap.', example: '<img src="../images/logo.png" alt="Logo">\n<a href="pages/about.html">Tentang</a>' },
  m25: { explanation: 'Pemisahan folder membuat project mudah dinavigasi. index.html menjadi pintu masuk, lalu images, css, js, dan pages menyimpan jenis asset atau halaman yang sesuai.', example: '<link rel="stylesheet" href="css/style.css">\n<script src="js/app.js"></script>\n<a href="pages/about.html">Tentang</a>' },
  m26: { explanation: 'Validasi HTML memeriksa doctype, penutupan tag, nesting, duplicate id, serta attribute yang sesuai. Valid markup membantu browser menghasilkan DOM yang konsisten dan mengurangi bug aksesibilitas.', example: '<!doctype html>\n<html lang="id"><body><p>Tag tertutup</p></body></html>' },
  m27: { explanation: 'Accessibility dimulai dari struktur yang bermakna. Alt menjelaskan gambar, label menjelaskan input, heading membentuk outline, semantic HTML memberi landmark, dan kontrol harus dapat dicapai melalui keyboard.', example: '<label for="photo">Foto profil</label>\n<input id="photo" type="file">\n<img src="profile.png" alt="Potret mahasiswa">' },
  m28: { explanation: 'SEO dasar berasal dari informasi yang jelas. title menjadi judul tab dan kandidat judul hasil pencarian, meta description memberi ringkasan, lalu heading dan semantic HTML membantu mesin memahami topik.', example: '<title>HTML Lab</title>\n<meta name="description" content="Belajar HTML dari dasar.">' },
  m29: { explanation: 'Best practice menjaga kode konsisten: indentasi rapi, nama file deskriptif, tag dan attribute huruf kecil, concern dipisah, serta tag deprecated dihindari. Kode yang mudah dibaca lebih mudah diuji dan dikembangkan.', example: '<link rel="stylesheet" href="css/style.css">\n<main>\n  <h1>HTML Lab</h1>\n</main>' },
  m30: { explanation: 'Halaman lengkap menggabungkan metadata, header, navigasi, main, section, konten, form atau tabel, dan footer. Mulai dari struktur semantic lalu tambahkan konten satu bagian demi satu bagian.', example: '<header>HTML Lab</header>\n<nav>Beranda</nav>\n<main><section><h2>Profil</h2></section></main>\n<footer>© 2026 HTML Lab</footer>' }
};

const challengeGuides = {
  'html-01': ['Buat satu elemen p.', 'Isi persis dengan kalimat “HTML menyusun struktur halaman.”', 'Pastikan p memiliki closing tag.'],
  'html-02': ['Mulai dengan <!doctype html>.', 'Buat html dengan lang="id".', 'Letakkan body di dalam dokumen.'],
  'html-03': ['Gunakan tag p.', 'Tambahkan class="intro".', 'Isi paragraf dengan “Halo, web!”.'],
  'html-04': ['Gunakan heading level 1.', 'Isi h1 dengan “Belajar Web”.'],
  'html-05': ['Buat p berisi “Baris pertama”.', 'Tambahkan br setelah paragraf.', 'Tambahkan hr sebagai pemisah topik.'],
  'html-06': ['Gunakan strong untuk “Penting”.', 'Gunakan em untuk “catatan”.'],
  'html-07': ['Buat link internal ke pages/about.html.', 'Buat link eksternal ke MDN.', 'Tambahkan target="_blank" pada link eksternal.'],
  'html-08': ['Gunakan img.', 'Isi src, alt, width="240", dan height="120" sesuai permintaan.', 'Ingat img tidak membutuhkan closing tag.'],
  'html-09': ['Gunakan ul.', 'Buat tiga li dengan urutan HTML, CSS, JavaScript.'],
  'html-10': ['Buat div sebagai container block.', 'Tempatkan span berisi “HTML Lab” di dalam div.'],
  'html-11': ['Buat seluruh landmark: header, nav, main, section, article, aside, footer.', 'Pastikan semua tag berada dalam struktur yang valid.'],
  'html-12': ['Buat table dengan thead, tbody, dan tfoot.', 'Header harus Nama dan Skor.', 'Gunakan colspan="2" pada ringkasan footer.'],
  'html-13': ['Buat form.', 'Tambahkan label, input, textarea, select-option, button, fieldset, dan legend.'],
  'html-14': ['Buat satu input untuk setiap type yang diminta.', 'Pastikan type tidak ditulis sebagai teks biasa.', 'Gunakan submit dan reset untuk aksi form.'],
  'html-15': ['Lengkapi attribute name, value, placeholder, required, maxlength, min, max, readonly.', 'Tambahkan checkbox checked dan option selected.'],
  'html-16': ['Buat audio dan video.', 'Tambahkan source di dalam masing-masing media.', 'Gunakan controls, loop, dan muted pada video.'],
  'html-17': ['Gunakan iframe.', 'Pakai URL YouTube embed.', 'Isi title agar frame aksesibel dan pertimbangkan sandbox.'],
  'html-18': ['Tampilkan contoh tag sebagai teks, bukan sebagai elemen HTML.', 'Gunakan entity untuk <, >, dan &.'],
  'html-19': ['Buat komentar HTML “Bagian utama”.', 'Tambahkan p berisi “Konten halaman” di bawahnya.'],
  'html-20': ['Buat satu div.', 'Tambahkan id, class, title, data-state, dan lang sesuai permintaan.'],
  'html-21': ['Buat section.', 'Tambahkan id="profile".', 'Tambahkan dua class: card dan highlight.'],
  'html-22': ['Buat div berisi “Block”.', 'Buat span berisi “Inline”.', 'Perhatikan perbedaan default block dan inline.'],
  'html-23': ['Buat p sebagai parent.', 'Tempatkan strong berisi “HTML” di dalam p.', 'Tutup strong sebelum menutup p.'],
  'html-24': ['Gunakan img.', 'Arahkan src ke ../images/logo.png.', 'Tambahkan alt="Logo”.'],
  'html-25': ['Hubungkan css/style.css dengan link stylesheet.', 'Buat anchor ke pages/about.html.'],
  'html-26': ['Mulai dengan doctype.', 'Buat html lang="id" dan title “Valid”.', 'Pastikan p “Rapi” tertutup.'],
  'html-27': ['Hubungkan label for="photo" dengan input id="photo".', 'Gunakan input type file.', 'Tambahkan alt bermakna pada img.'],
  'html-28': ['Buat title “HTML Lab”.', 'Buat meta name="description".', 'Isi content dengan “Belajar HTML dari dasar.”.'],
  'html-29': ['Gunakan tag dan attribute huruf kecil.', 'Hubungkan stylesheet eksternal.', 'Buat main dengan h1 yang terindentasi rapi.'],
  'html-30': ['Buat header dan nav.', 'Buat main berisi section dan h2 “Profil”.', 'Tutup halaman dengan footer.']
};

moduleCatalog.forEach((module) => Object.assign(module, detailedNotes[module.id]));
questions.forEach((question) => {
  question.steps = challengeGuides[question.id];
  question.hint = question.hint || question.steps?.[0] || 'Ikuti instruksi, tulis HTML secara manual, lalu periksa hasilnya.';
});

window.COURSE = {
  slug: 'html-foundations-complete',
  title: 'HTML // FOUNDATIONS COMPLETE',
  label: 'WEB DEVELOPMENT · 30 TOPICS',
  description: 'Kuasai fondasi HTML dari tag pertama sampai halaman web lengkap.',
  modules: moduleCatalog,
  questions
};

window.COURSE_CHECKS = {
  'html-01': [{ kind: 'elementText', tag: 'p', text: 'HTML menyusun struktur halaman.' }],
  'html-02': [{ kind: 'doctype' }, { kind: 'attribute', tag: 'html', attr: 'lang', value: 'id' }, { kind: 'hasTags', tags: ['body'] }],
  'html-03': [{ kind: 'attribute', tag: 'p', attr: 'class', value: 'intro' }, { kind: 'elementText', tag: 'p', text: 'Halo, web!' }],
  'html-04': [{ kind: 'elementText', tag: 'h1', text: 'Belajar Web' }],
  'html-05': [{ kind: 'elementText', tag: 'p', text: 'Baris pertama' }, { kind: 'hasTags', tags: ['br', 'hr'] }],
  'html-06': [{ kind: 'elementText', tag: 'strong', text: 'Penting' }, { kind: 'elementText', tag: 'em', text: 'catatan' }],
  'html-07': [{ kind: 'attribute', tag: 'a', attr: 'href', value: 'pages/about.html' }, { kind: 'hasAttribute', tag: 'a', attr: 'target', value: '_blank' }],
  'html-08': [{ kind: 'attribute', tag: 'img', attr: 'src', value: 'images/logo.png' }, { kind: 'attribute', tag: 'img', attr: 'alt', value: 'Logo HTML Lab' }, { kind: 'attribute', tag: 'img', attr: 'width', value: '240' }, { kind: 'attribute', tag: 'img', attr: 'height', value: '120' }],
  'html-09': [{ kind: 'listText', tag: 'ul', values: ['HTML', 'CSS', 'JavaScript'] }],
  'html-10': [{ kind: 'containsElementText', parent: 'div', child: 'span', text: 'HTML Lab' }],
  'html-11': [{ kind: 'hasTags', tags: ['header', 'nav', 'main', 'section', 'article', 'aside', 'footer'] }],
  'html-12': [{ kind: 'hasTags', tags: ['table', 'thead', 'tbody', 'tfoot'] }, { kind: 'tableHeaders', values: ['Nama', 'Skor'] }, { kind: 'hasAttribute', tag: 'td', attr: 'colspan', value: '2' }],
  'html-13': [{ kind: 'hasTags', tags: ['form', 'label', 'input', 'textarea', 'select', 'option', 'button', 'fieldset', 'legend'] }],
  'html-14': [{ kind: 'inputTypes', values: ['text', 'password', 'email', 'number', 'date', 'radio', 'checkbox', 'file', 'color', 'range', 'submit', 'reset'] }],
  'html-15': [{ kind: 'hasAttributes', attrs: [{ tag: 'input', attr: 'name' }, { tag: 'input', attr: 'value' }, { tag: 'input', attr: 'placeholder' }, { tag: 'input', attr: 'required' }, { tag: 'input', attr: 'maxlength' }, { tag: 'input', attr: 'min' }, { tag: 'input', attr: 'max' }, { tag: 'input', attr: 'readonly' }] }, { kind: 'hasAttribute', tag: 'input', attr: 'checked' }, { kind: 'hasAttribute', tag: 'option', attr: 'selected' }],
  'html-16': [{ kind: 'hasTags', tags: ['audio', 'video', 'source'] }, { kind: 'hasAttribute', tag: 'audio', attr: 'controls' }, { kind: 'hasAttribute', tag: 'video', attr: 'muted' }],
  'html-17': [{ kind: 'iframeEmbed', requireTitle: true }],
  'html-18': [{ kind: 'elementText', tag: 'p', text: '<h1>HTML</h1> & aman' }],
  'html-19': [{ kind: 'comment', text: 'Bagian utama' }, { kind: 'elementText', tag: 'p', text: 'Konten halaman' }],
  'html-20': [{ kind: 'attribute', tag: 'div', attr: 'id', value: 'app' }, { kind: 'attribute', tag: 'div', attr: 'class', value: 'card' }, { kind: 'attribute', tag: 'div', attr: 'data-state', value: 'ready' }, { kind: 'attribute', tag: 'div', attr: 'lang', value: 'id' }],
  'html-21': [{ kind: 'attribute', tag: 'section', attr: 'id', value: 'profile' }, { kind: 'attribute', tag: 'section', attr: 'class', value: 'card highlight' }],
  'html-22': [{ kind: 'elementText', tag: 'div', text: 'Block' }, { kind: 'elementText', tag: 'span', text: 'Inline' }],
  'html-23': [{ kind: 'containsElementText', parent: 'p', child: 'strong', text: 'HTML' }],
  'html-24': [{ kind: 'attribute', tag: 'img', attr: 'src', value: '../images/logo.png' }, { kind: 'attribute', tag: 'img', attr: 'alt', value: 'Logo' }],
  'html-25': [{ kind: 'attribute', tag: 'link', attr: 'href', value: 'css/style.css' }, { kind: 'attribute', tag: 'a', attr: 'href', value: 'pages/about.html' }],
  'html-26': [{ kind: 'doctype' }, { kind: 'attribute', tag: 'html', attr: 'lang', value: 'id' }, { kind: 'elementText', tag: 'title', text: 'Valid' }, { kind: 'elementText', tag: 'p', text: 'Rapi' }],
  'html-27': [{ kind: 'attribute', tag: 'img', attr: 'alt', value: 'Potret mahasiswa' }, { kind: 'labelInput', labelFor: 'photo', inputId: 'photo', text: 'Foto profil' }],
  'html-28': [{ kind: 'elementText', tag: 'title', text: 'HTML Lab' }, { kind: 'metaContent', name: 'description', content: 'Belajar HTML dari dasar.' }],
  'html-29': [{ kind: 'attribute', tag: 'link', attr: 'rel', value: 'stylesheet' }, { kind: 'attribute', tag: 'link', attr: 'href', value: 'css/style.css' }, { kind: 'hasTags', tags: ['main', 'h1'] }],
  'html-30': [{ kind: 'hasTags', tags: ['header', 'nav', 'main', 'section', 'footer'] }, { kind: 'containsElementText', parent: 'section', child: 'h2', text: 'Profil' }]
};

window.VISUAL_CHALLENGES = {
  'html-04': { label: 'TARGET BROWSER OUTPUT', html: '<h1>Belajar Web</h1>', clue: 'Gunakan heading utama. Elemen paling penting di halaman biasanya memakai h1.' },
  'html-05': { label: 'TARGET BROWSER OUTPUT', html: '<p>Baris pertama</p><br><hr>', clue: 'Tampilkan satu paragraf, pindah baris, lalu beri pemisah topik.' },
  'html-09': { label: 'TARGET BROWSER OUTPUT', html: '<ul><li>HTML</li><li>CSS</li><li>JavaScript</li></ul>', clue: 'Daftar ini tidak memakai nomor. Gunakan list tanpa urutan dan item di dalamnya.' },
  'html-10': { label: 'TARGET BROWSER OUTPUT', html: '<div class="target-card"><span>HTML Lab</span></div>', clue: 'Kelompokkan elemen dengan container block dan inline.' },
  'html-12': { label: 'TARGET BROWSER OUTPUT', html: '<table><thead><tr><th>Nama</th><th>Skor</th></tr></thead><tbody><tr><td>Ana</td><td>90</td></tr></tbody></table>', clue: 'Tampilan ini berasal dari data yang disusun dalam baris dan kolom.' },
  'html-14': { label: 'TARGET BROWSER OUTPUT', html: '<label>Email</label><br><input type="email" placeholder="nama@email.com">', clue: 'Field ini khusus alamat email. Pilih input type yang memberi validasi email.' },
  'html-17': { label: 'TARGET BROWSER OUTPUT', html: '<iframe title="Video pengantar HTML" style="width:100%;height:90px;border:1px solid #ccd4e8"></iframe>', clue: 'Konten eksternal tampil sebagai frame di dalam halaman.' },
  'html-20': { label: 'TARGET BROWSER OUTPUT', html: '<div id="app" class="card">Profil mahasiswa</div>', clue: 'Elemen ini punya identitas unik, class, dan metadata global.' },
  'html-23': { label: 'TARGET BROWSER OUTPUT', html: '<p><strong>HTML</strong> rapi.</p>', clue: 'Teks penting berada di dalam paragraf. Perhatikan urutan nesting dan penutupan tag.' },
  'html-30': { label: 'TARGET BROWSER OUTPUT', html: '<header>HTML Lab</header><nav>Beranda</nav><main><section><h2>Profil</h2></section></main><footer>© 2026 HTML Lab</footer>', clue: 'Gabungkan landmark semantic untuk membuat satu halaman lengkap.' }
};
