/*
 * Content is intentionally separated from the interface.
 * To create another topic (for example CSS), replace course title, modules,
 * and questions below while keeping the same question contract.
 */
window.COURSE = {
  slug: 'html-foundations',
  title: 'HTML // FOUNDATIONS',
  label: 'WEB DEVELOPMENT · LEVEL 01',
  description: 'Mulai dari satu tag, lalu bangun dunia digitalmu sendiri.',
  modules: [
    { id: 'structure', number: '01', title: 'Struktur dokumen', icon: '⌘', description: 'Kenali kerangka utama sebuah halaman HTML.' },
    { id: 'content', number: '02', title: 'Konten & teks', icon: 'Aa', description: 'Buat heading, paragraf, link, dan gambar yang bermakna.' },
    { id: 'semantic', number: '03', title: 'Semantic HTML', icon: '◫', description: 'Susun halaman dengan tag yang punya arti dan konteks.' },
    { id: 'forms', number: '04', title: 'Form & data', icon: '⌁', description: 'Hubungkan pengguna dengan halaman melalui form.' }
  ],
  questions: [
    { id: 'html-01', module: 'structure', title: 'Declare the document', prompt: 'Lengkapi baris pertama agar browser membaca dokumen ini sebagai HTML5.', lessonTitle: 'Kenalan dengan HTML5', lessonBody: 'Deklarasi doctype memberi tahu browser standar HTML yang digunakan. Ia bukan tag, tetapi selalu berada paling atas dokumen.', lessonCode: '<!doctype html>\n<html lang="id">\n  ...\n</html>', starter: '<!-- Tulis deklarasi HTML5 di sini -->', required: ['<!doctype\\s+html>'], hint: 'Diawali dengan <! dan menyebut html.' },
    { id: 'html-02', module: 'structure', title: 'Set the document language', prompt: 'Tambahkan atribut bahasa Indonesia pada tag pembuka html.', lessonTitle: 'Atribut pada tag', lessonBody: 'Atribut memberi informasi tambahan pada sebuah tag. Atribut lang membantu browser dan screen reader memahami bahasa halaman.', lessonCode: '<html lang="id">\n  <head>...</head>\n  <body>...</body>\n</html>', starter: '<!doctype html>\n<html>\n  <!-- tambahkan atribut bahasa -->\n</html>', required: ['<html[^>]*\\blang\\s*=\\s*["\']id["\']'], hint: 'Gunakan lang="id" di dalam tag html.' },
    { id: 'html-03', module: 'structure', title: 'Describe the character set', prompt: 'Lengkapi bagian head agar mendukung karakter UTF-8.', lessonTitle: 'Head vs body', lessonBody: 'Elemen head menyimpan metadata. UTF-8 adalah encoding yang aman untuk karakter dan bahasa di seluruh dunia.', lessonCode: '<head>\n  <meta charset="UTF-8">\n  <title>HTML Lab</title>\n</head>', starter: '<head>\n  <!-- metadata charset di sini -->\n</head>', required: ['<meta[^>]*charset\\s*=\\s*["\']?utf-8'], hint: 'Nama metadatanya charset dan nilainya UTF-8.' },
    { id: 'html-04', module: 'structure', title: 'Name the browser tab', prompt: 'Buat judul tab halaman menjadi “HTML Lab”.', lessonTitle: 'Judul halaman', lessonBody: 'Tag title berada di dalam head. Isinya muncul di tab browser dan membantu mesin pencari mengenali halaman.', lessonCode: '<title>HTML Lab</title>', starter: '<head>\n  <!-- buat title di sini -->\n</head>', required: ['<title\\s*>\\s*html\\s+lab\\s*</title>'], hint: 'Gunakan pasangan tag title dengan teks HTML Lab.' },
    { id: 'html-05', module: 'content', title: 'Create the hero heading', prompt: 'Gunakan heading level 1 untuk menulis teks “Belajar HTML”.', lessonTitle: 'Hierarki heading', lessonBody: 'Heading membentuk hierarki konten. h1 biasanya menjadi judul utama halaman dan idealnya hanya ada satu yang paling dominan.', lessonCode: '<h1>Belajar HTML</h1>\n<h2>Mulai dari dasar</h2>', starter: '<!-- Heading utama di sini -->', required: ['<h1\\s*>\\s*belajar\\s+html\\s*</h1>'], hint: 'Tag heading paling besar adalah h1.' },
    { id: 'html-06', module: 'content', title: 'Write a paragraph', prompt: 'Bungkus kalimat “HTML itu menyenangkan.” dengan tag paragraf.', lessonTitle: 'Teks paragraf', lessonBody: 'Tag p dipakai untuk blok paragraf. Browser otomatis memberi jarak visual antar paragraf, sehingga struktur tetap mudah dibaca.', lessonCode: '<p>HTML itu menyenangkan.</p>', starter: '<!-- Jadikan kalimat ini sebuah paragraf -->\nHTML itu menyenangkan.', required: ['<p\\s*>\\s*html\\s+itu\\s+menyenangkan\\.\\s*</p>'], hint: 'Buka dengan p, tutup dengan /p.' },
    { id: 'html-07', module: 'content', title: 'Link to the future', prompt: 'Buat link bertuliskan “Kunjungi MDN” menuju https://developer.mozilla.org.', lessonTitle: 'Anchor & hyperlink', lessonBody: 'Anchor memakai atribut href untuk menentukan tujuan link. Isi teksnya harus menjelaskan ke mana pengguna akan pergi.', lessonCode: '<a href="https://developer.mozilla.org">\n  Kunjungi MDN\n</a>', starter: '<!-- Buat link dokumentasi -->', required: ['<a[^>]*href\\s*=\\s*["\']https://developer\\.mozilla\\.org["\'][^>]*>\\s*kunjungi\\s+mdn\\s*</a>'], hint: 'href adalah alamat tujuan link.' },
    { id: 'html-08', module: 'content', title: 'Give an image context', prompt: 'Tambahkan gambar dengan src “avatar.png” dan alt “Foto profil mahasiswa”.', lessonTitle: 'Image yang aksesibel', lessonBody: 'Tag img tidak memiliki tag penutup. Atribut alt memberi deskripsi ketika gambar gagal dimuat atau dibaca oleh screen reader.', lessonCode: '<img src="avatar.png" alt="Foto profil mahasiswa">', starter: '<!-- Tambahkan gambar profil -->', required: ['<img[^>]*src\\s*=\\s*["\']avatar\\.png["\']', '<img[^>]*alt\\s*=\\s*["\']foto profil mahasiswa["\']'], hint: 'img butuh src dan alt.' },
    { id: 'html-09', module: 'content', title: 'List your tools', prompt: 'Buat unordered list berisi HTML dan CSS.', lessonTitle: 'Unordered list', lessonBody: 'ul membuat daftar tanpa urutan. Setiap item harus berada di dalam li agar browser dan teknologi bantu memahami struktur daftar.', lessonCode: '<ul>\n  <li>HTML</li>\n  <li>CSS</li>\n</ul>', starter: '<!-- Daftar tools favoritmu -->', required: ['<ul\\s*>[\\s\\S]*<li\\s*>\\s*html\\s*</li>[\\s\\S]*<li\\s*>\\s*css\\s*</li>[\\s\\S]*</ul>'], hint: 'Gunakan ul sebagai pembungkus dan dua li sebagai item.' },
    { id: 'html-10', module: 'content', title: 'Order the steps', prompt: 'Buat ordered list berisi tiga langkah: Riset, Kode, Rilis.', lessonTitle: 'Ordered list', lessonBody: 'ol digunakan saat urutan item punya makna. Browser biasanya menampilkan nomor otomatis tanpa perlu mengetiknya manual.', lessonCode: '<ol>\n  <li>Riset</li>\n  <li>Kode</li>\n  <li>Rilis</li>\n</ol>', starter: '<!-- Langkah membuat produk digital -->', required: ['<ol\\s*>[\\s\\S]*<li\\s*>\\s*riset\\s*</li>[\\s\\S]*<li\\s*>\\s*kode\\s*</li>[\\s\\S]*<li\\s*>\\s*rilis\\s*</li>[\\s\\S]*</ol>'], hint: 'Berbeda dengan ul, ordered list memakai ol.' },
    { id: 'html-11', module: 'semantic', title: 'Build the top bar', prompt: 'Gunakan tag semantic header untuk membungkus teks “HTML Lab”.', lessonTitle: 'Header semantic', lessonBody: 'Tag semantic menjelaskan peran konten. header biasanya berisi pengantar halaman atau area navigasi pembuka.', lessonCode: '<header>\n  <strong>HTML Lab</strong>\n</header>', starter: '<!-- Area paling atas halaman -->\nHTML Lab', required: ['<header\\s*>[\\s\\S]*html\\s+lab[\\s\\S]*</header>'], hint: 'Bungkus konten bagian atas dengan header.' },
    { id: 'html-12', module: 'semantic', title: 'Make navigation clear', prompt: 'Bungkus link “Beranda” dengan tag nav.', lessonTitle: 'Navigasi semantic', lessonBody: 'nav menandai sekumpulan link navigasi utama. Ini membuat struktur halaman lebih jelas untuk browser, mesin pencari, dan screen reader.', lessonCode: '<nav>\n  <a href="/">Beranda</a>\n</nav>', starter: '<!-- Navigasi halaman -->\n<a href="/">Beranda</a>', required: ['<nav\\s*>[\\s\\S]*<a[^>]*>\\s*beranda\\s*</a>[\\s\\S]*</nav>'], hint: 'nav dapat membungkus satu atau beberapa link.' },
    { id: 'html-13', module: 'semantic', title: 'Define the main area', prompt: 'Gunakan tag main untuk membungkus teks “Konten utama”.', lessonTitle: 'Main content', lessonBody: 'Satu halaman idealnya memiliki satu main. Elemen ini menandai konten utama yang unik, bukan navigasi atau informasi berulang.', lessonCode: '<main>\n  <h1>Konten utama</h1>\n</main>', starter: '<!-- Konten inti halaman -->\nKonten utama', required: ['<main\\s*>[\\s\\S]*konten\\s+utama[\\s\\S]*</main>'], hint: 'Area inti halaman menggunakan main.' },
    { id: 'html-14', module: 'semantic', title: 'Group a focused topic', prompt: 'Buat section dengan id “tentang” yang berisi heading “Tentang kelas”.', lessonTitle: 'Section & id', lessonBody: 'section mengelompokkan bagian yang memiliki tema. id memberi identitas unik yang bisa dipakai untuk anchor link atau styling CSS.', lessonCode: '<section id="tentang">\n  <h2>Tentang kelas</h2>\n</section>', starter: '<!-- Section profil kelas -->', required: ['<section[^>]*\\bid\\s*=\\s*["\']tentang["\'][^>]*>[\\s\\S]*<h2\\s*>\\s*tentang kelas\\s*</h2>[\\s\\S]*</section>'], hint: 'Pasang id="tentang" pada section.' },
    { id: 'html-15', module: 'semantic', title: 'Publish an article', prompt: 'Gunakan article untuk membungkus judul “Catatan belajar”.', lessonTitle: 'Article', lessonBody: 'article cocok untuk konten mandiri seperti posting, berita, atau catatan yang tetap masuk akal jika dipisahkan dari halaman.', lessonCode: '<article>\n  <h2>Catatan belajar</h2>\n  <p>...</p>\n</article>', starter: '<!-- Satu catatan mandiri -->\n<h2>Catatan belajar</h2>', required: ['<article\\s*>[\\s\\S]*<h2\\s*>\\s*catatan belajar\\s*</h2>[\\s\\S]*</article>'], hint: 'Bungkus seluruh konten catatan dalam article.' },
    { id: 'html-16', module: 'forms', title: 'Label your input', prompt: 'Buat label “Nama lengkap” yang terhubung ke input dengan id “full-name”.', lessonTitle: 'Label & input', lessonBody: 'label menjelaskan input dan atribut for harus sama dengan id input. Hubungan ini membuat form lebih mudah digunakan dan lebih aksesibel.', lessonCode: '<label for="full-name">Nama lengkap</label>\n<input id="full-name" type="text">', starter: '<!-- Field nama -->', required: ['<label[^>]*\\bfor\\s*=\\s*["\']full-name["\'][^>]*>\\s*nama lengkap\\s*</label>[\\s\\S]*<input[^>]*\\bid\\s*=\\s*["\']full-name["\']'], hint: 'for pada label harus sama persis dengan id input.' },
    { id: 'html-17', module: 'forms', title: 'Collect an email', prompt: 'Tambahkan input email dengan name “email” dan atribut required.', lessonTitle: 'Input type', lessonBody: 'type="email" memberi petunjuk browser untuk memvalidasi format alamat email. required membuat field wajib diisi.', lessonCode: '<input type="email" name="email" required>', starter: '<!-- Field email wajib -->', required: ['<input[^>]*\\btype\\s*=\\s*["\']email["\']', '<input[^>]*\\bname\\s*=\\s*["\']email["\']', '<input[^>]*\\brequired'], hint: 'Pastikan ada type email, name email, dan required.' },
    { id: 'html-18', module: 'forms', title: 'Submit the form', prompt: 'Buat button bertuliskan “Kirim jawaban” dengan type submit.', lessonTitle: 'Button action', lessonBody: 'Button adalah kontrol interaktif. type="submit" memberi tahu browser bahwa tombol akan mengirim form terdekat.', lessonCode: '<button type="submit">Kirim jawaban</button>', starter: '<!-- Tombol kirim form -->', required: ['<button[^>]*\\btype\\s*=\\s*["\']submit["\'][^>]*>\\s*kirim jawaban\\s*</button>'], hint: 'Atribut type membedakan submit, button, dan reset.' },
    { id: 'html-19', module: 'forms', title: 'Show structured data', prompt: 'Buat tabel dengan header kolom “Nama” dan “Skor” menggunakan thead.', lessonTitle: 'Tabel data', lessonBody: 'Gunakan table untuk data tabular. thead menandai baris header, sedangkan th adalah sel header yang menjelaskan kolom.', lessonCode: '<table>\n  <thead>\n    <tr><th>Nama</th><th>Skor</th></tr>\n  </thead>\n</table>', starter: '<!-- Tabel hasil belajar -->', required: ['<table\\s*>[\\s\\S]*<thead\\s*>[\\s\\S]*<th\\s*>\\s*nama\\s*</th>[\\s\\S]*<th\\s*>\\s*skor\\s*</th>[\\s\\S]*</thead>'], hint: 'Header tabel berada di dalam thead, lalu tr dan th.' },
    { id: 'html-20', module: 'forms', title: 'Embed a video', prompt: 'Sematkan video “intro.mp4” dengan kontrol pemutar terlihat.', lessonTitle: 'Media element', lessonBody: 'Elemen video menampilkan media langsung di halaman. Atribut controls menampilkan kontrol play, pause, dan volume bawaan browser.', lessonCode: '<video src="intro.mp4" controls>\n  Browser kamu belum mendukung video.\n</video>', starter: '<!-- Video pengantar kelas -->', required: ['<video[^>]*\\bsrc\\s*=\\s*["\']intro\\.mp4["\'][^>]*\\bcontrols'], hint: 'Gunakan tag video, src intro.mp4, dan controls.' }
  ]
};

// Structural checks make the challenge flexible: whitespace, quote style,
// and attribute order can vary as long as the HTML meaning is correct.
window.COURSE_CHECKS = {
  'html-01': [{ kind: 'doctype' }],
  'html-02': [{ kind: 'attribute', tag: 'html', attr: 'lang', value: 'id' }],
  'html-03': [{ kind: 'attribute', tag: 'meta', attr: 'charset', value: 'utf-8' }],
  'html-04': [{ kind: 'elementText', tag: 'title', text: 'HTML Lab' }],
  'html-05': [{ kind: 'elementText', tag: 'h1', text: 'Belajar HTML' }],
  'html-06': [{ kind: 'elementText', tag: 'p', text: 'HTML itu menyenangkan.' }],
  'html-07': [{ kind: 'attribute', tag: 'a', attr: 'href', value: 'https://developer.mozilla.org' }, { kind: 'elementText', tag: 'a', text: 'Kunjungi MDN' }],
  'html-08': [{ kind: 'attribute', tag: 'img', attr: 'src', value: 'avatar.png' }, { kind: 'attribute', tag: 'img', attr: 'alt', value: 'Foto profil mahasiswa' }],
  'html-09': [{ kind: 'listText', tag: 'ul', values: ['HTML', 'CSS'] }],
  'html-10': [{ kind: 'listText', tag: 'ol', values: ['Riset', 'Kode', 'Rilis'] }],
  'html-11': [{ kind: 'containsText', tag: 'header', text: 'HTML Lab' }],
  'html-12': [{ kind: 'containsElementText', parent: 'nav', child: 'a', text: 'Beranda' }],
  'html-13': [{ kind: 'containsText', tag: 'main', text: 'Konten utama' }],
  'html-14': [{ kind: 'attribute', tag: 'section', attr: 'id', value: 'tentang' }, { kind: 'elementText', tag: 'h2', text: 'Tentang kelas' }],
  'html-15': [{ kind: 'containsElementText', parent: 'article', child: 'h2', text: 'Catatan belajar' }],
  'html-16': [{ kind: 'labelInput', labelFor: 'full-name', inputId: 'full-name', text: 'Nama lengkap' }],
  'html-17': [{ kind: 'inputAttributes', type: 'email', name: 'email', required: true }],
  'html-18': [{ kind: 'button', type: 'submit', text: 'Kirim jawaban' }],
  'html-19': [{ kind: 'tableHeaders', values: ['Nama', 'Skor'] }],
  'html-20': [{ kind: 'media', tag: 'video', attr: 'src', value: 'intro.mp4', requiredAttr: 'controls' }]
};
